name: locations
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2
  persian_datetime_picker: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.11
  flutter_lints: ^4.0.0
  sqflite: 2.3.3+1
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  intl: ^0.18.1
  geolocator: ^10.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/vazirmatn.ttf
          weight: 600

    - family: bold
      fonts:
        - asset: assets/fonts/BTitrBold.ttf
          weight: 700

    - family: light
      fonts:
        - asset: assets/fonts/vazirmatn.ttf
          weight: 600

    - family: body
      fonts:
        - asset: assets/fonts/vazirmatn.ttf
          weight: 300

    - family: bold_yekan
      fonts:
        - asset: assets/fonts/BYekanBold.ttf
          weight: 800
  plugin:
    platforms:
      android:
        package: com.example.locations
        pluginClass: LocationsPlugin
      ios:
        pluginClass: LocationsPlugin
      web:
        pluginClass: LocationsWeb
        fileName: locations_web.dart


